repos:
  - repo: https://github.com/gitguardian/gg-shield
    rev: v1.15.0
    hooks:
      - id: ggshield-commit-hook
        name: GitGuardian
        entry: ggshield scan pre-commit
        language: python
        types: [text, python, javascript, json, yaml, env, bash, dockerfile]
        pass_filenames: true
        always_run: true
        verbose: true

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        additional_dependencies: ['detect-secrets>=1.0.0']

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        name: bandit-security-check
        entry: bandit -r src
        language: python
        language_version: python3
        types: [python]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
