@echo off
echo Stopping any process on port 5173...
for /f "tokens=5" %%a in ('netstat -ano ^| findstr :5173 ^| findstr LISTENING') do (
    echo Killing process ID %%a...
    taskkill /F /PID %%a
)

cd /d "%~dp0casestrainer-vue-new"
echo Starting Vue development server...
start "" cmd /k "npm run dev"
echo Vue development server is starting...
pause
