services:
  redis:
    image: redis:7-alpine
    container_name: casestrainer-redis-dev
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  casestrainer:
    build: .
    container_name: casestrainer-dev
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - SECRET_KEY=2b6e7c8e-4f1a-4e2b-9c3d-7f8e1a2b3c4d
      - FLASK_APP=src/app_final_vue.py
      - FLASK_ENV=production
      - APPLICATION_ROOT=/casestrainer
      - USE_WAITRESS=true
      - REDIS_URL=redis://casestrainer-redis-prod:6379/0
      - DATABASE_FILE=/app/data/citations.db
      - UPLOAD_FOLDER=/app/uploads
      - TEMP_FOLDER=/app/temp_uploads
      - LOG_LEVEL=INFO
    volumes:
      - ../config.json:/app/config.json:ro
      - ../data:/app/data
      - ../uploads:/app/uploads
      - ../temp_uploads:/app/temp_uploads
      - ../logs:/app/logs
    ports:
      - "5001:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/casestrainer/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  nginx:
    image: nginx:alpine
    container_name: casestrainer-nginx-dev
    restart: always
    depends_on:
      casestrainer:
        condition: service_healthy
    ports:
      - "8081:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ../uploads:/var/www/uploads:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/casestrainer/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
