services:
  redis:
    image: redis:7-alpine
    container_name: casestrainer-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - casestrainer_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  casestrainer:
    build: .
    container_name: casestrainer
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - casestrainer_network
    environment:
      - SECRET_KEY=2b6e7c8e-4f1a-4e2b-9c3d-7f8e1a2b3c4d
      - FLASK_APP=src/app_final_vue.py
      - FLASK_ENV=production
      - APPLICATION_ROOT=/casestrainer
      - USE_WAITRESS=true
      - REDIS_URL=redis://casestrainer-redis:6379/0
    volumes:
      - ../config.json:/app/config.json
      - ../src:/app/src
      - ../flask_session:/app/flask_session

  nginx:
    image: nginx:latest
    container_name: casestrainer-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
    depends_on:
      - casestrainer
    restart: always
    networks:
      - casestrainer_network

volumes:
  redis_data:

networks:
  casestrainer_network:
    driver: bridge
