version: '3.8'

services:
  frontend:
    image: node:18-alpine
    container_name: vue-dev-temp
    working_dir: /app
    volumes:
      - ../casestrainer-vue-new:/app
    ports:
      - "5176:5173"
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
