#!/usr/bin/env python3
"""
Interactive script to set up environment variables for CaseStrainer.
This script helps users create a .env file with the required configuration.
"""

import os
import sys
from pathlib import Path

def main():
    print("=== CaseStrainer Environment Setup ===\n")
    
    # Check if .env already exists
    env_path = Path(".env")
    if env_path.exists():
        print("A .env file already exists.")
        overwrite = input("Do you want to overwrite it? (y/N): ").strip().lower()
        if overwrite != 'y':
            print("Setup cancelled. No changes were made.")
            return
    
    # Get configuration values
    print("\nPlease provide the following configuration values:")
    
    # Get CourtListener API key
    courtlistener_key = input(
        "\n1. Enter your CourtListener API key (required for citation validation):\n"
        "   Leave empty if you don't have one. You can get one at https://www.courtlistener.com/api/
"
        "CourtListener API key: "
    ).strip()
    
    # Get LangSearch API key
    langsearch_key = input(
        "\n2. Enter your LangSearch API key (optional, press Enter to skip): "
    ).strip()
    
    # Generate a secret key if needed
    import secrets
    secret_key = secrets.token_hex(32)
    
    # Get upload folder path
    upload_folder = input(
        f"\n3. Enter the upload folder path (default: 'uploads'): "
    ).strip() or 'uploads'
    
    # Get database file path
    db_file = input(
        f"\n4. Enter the database file path (default: 'citations.db'): "
    ).strip() or 'citations.db'
    
    # Prepare environment variables
    env_content = f"""# CaseStrainer Environment Configuration
# Generated by setup_env.py

# Required settings
SECRET_KEY={secret_key}
DATABASE_FILE={db_file}
UPLOAD_FOLDER={upload_folder}

# API Keys
COURTLISTENER_API_KEY={courtlistener_key or 'your-courtlistener-api-key'}
LANGSEARCH_API_KEY={langsearch_key or 'your-langsearch-api-key'}

# Session configuration
SESSION_TYPE=filesystem
SESSION_FILE_DIR=casestrainer_sessions
SESSION_COOKIE_PATH=/casestrainer/

# CourtListener API configuration
COURTLISTENER_API_URL=https://www.courtlistener.com/api/rest/v4/opinions/

# Uncomment and configure if using Sentry for error tracking
# SENTRY_DSN=your-sentry-dsn
"""
    
    # Write to .env file
    try:
        with open(env_path, 'w') as f:
            f.write(env_content)
        
        print(f"\n✅ Successfully created {env_path}")
        print("\nNext steps:")
        print("1. Review the generated .env file and make any necessary adjustments")
        print("2. Never commit this file to version control")
        print("3. Start the application using 'start_casestrainer.bat'")
        
    except Exception as e:
        print(f"\n❌ Error creating .env file: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
